### ISSUE TITLE
README: describe how to use no_std

### ISSUE THREAD

**Issue by xobs** [RustCrypto/hashes#105]
Currently, the README states that it's possible to use these crates with `no_std`.  However, it does not say how to do so.

A simple one-line example for `Cargo.toml` would be nice.

**Comment by xobs** [comment]
For example, my first attempt was this:

```toml
[dependencies.sha3]
features = []
version = "0.8.2"
```

This does not work.  The correct syntax is:

```toml
[dependencies.sha3]
default-features = false
version = "0.8.2"
```
