### ISSUE TITLE
Hash functions not working on bare metal

### ISSUE THREAD

**Issue by KRACK-BIT** [RustCrypto/hashes#452]
Hi, I'm trying to follow the basic demo for `sha3` directly on a micro controller, but every time I invoke `hasher.finalize()`, it crashes.

Original message: https://rustcrypto.zulipchat.com/#narrow/stream/260036-general/topic/Kyber/near/327275368

Every time I invoke `hasher.finalize()` on my microcontroller, it will crash, no matter the data I'm using; it jumps to cortex_m_rt::DefaultHandler_ () and does not progress any further.

The below code I'm running is meant to follow the sample code for sha3 almost identically:
```rust
#![no_main]
#![no_std]

use panic_semihosting as _; // you can put a breakpoint on `rust_begin_unwind` to catch panics
                            // use panic_abort as _; // requires nightly
                            // use panic_itm as _; // logs messages over ITM; requires ITM support
                            // use panic_semihosting as _; // logs messages to the host stderr; requires a debugger

use cortex_m_rt::entry;
use cortex_m_semihosting::hprintln;

#[entry]
fn main() -> ! {
    use sha3::{Digest, Sha3_256};

    let mut hasher = Sha3_256::new();
    let data = b"Hello world!";
    hasher.update(data);
    // `update` can be called repeatedly and is generic over `AsRef<[u8]>`
    hasher.update("String data");
    // Note that calling `finalize()` consumes hasher
    hprintln!("hasher finalizing input");
    let hash = hasher.finalize();
    hprintln!("hasher finalized input");
    hprintln!("Binary hash: {:?}", hash);

    loop {
        panic!("Done!")
    }
}
```
I'm running this on an `xmc4500` microcontroller, my build command is `cargo run --target thumbv7em-none-eabihf --example sha3`, I'm debugging in `gdb` and this is connecting to `openocd`. I'm not sure if there's maybe something I'm missing, but are there any pitfalls I'm missing for when running RustCrypto modules on hardware?

**Comment by tarcieri** [comment]
There's nothing specific to `no_std` targets which would cause an incompatibility. These crates should work fine on Cortex-M targets, although we don't exactly CI them directly on bare metal hardware.

It sounds like this might be a panic? If you have semihosting set up on your device, can you get the panic message? That's the next thing we really need to debug.

**Comment by pinkforest** [comment]
So the crash in actual microcontroller is with both nightly and stable and not just debugger red herring ?

I've asked couple of smart embedded people

I thought first it might be something to do with target..

xmc4500 is Cortex-M4 which seems correct as Cortex-M4 which has FPU thus `thumbv7em-none-eabi`

```
The Cortex-M4 FPU is an implementation of the single precision variant of the ARMv7-M Floating-Point Extension (FPv4-SP). It provides floating-point computation functionality that is compliant with the ANSI/IEEE Std 754-2008, IEEE Standard for Binary Floating-Point Arithmetic, referred to as the IEEE 754 standard.
```

Looking at: https://github.com/rust-embedded/cortex-m-quickstart

```toml
[build]
# Pick ONE of these compilation targets
# target = "thumbv6m-none-eabi"    # Cortex-M0 and Cortex-M0+
# target = "thumbv7m-none-eabi"    # Cortex-M3
# target = "thumbv7em-none-eabi"   # Cortex-M4 and Cortex-M7 (no FPU)
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)
# target = "thumbv8m.base-none-eabi"   # Cortex-M23
# target = "thumbv8m.main-none-eabi"   # Cortex-M33 (no FPU)
# target = "thumbv8m.main-none-eabihf" # Cortex-M33 (with FPU)
```

This all seems kosher.

I wonder off curiosity what happens if you use `thumbv7em-none-eabi`

To me this seems some kind of toolchain problem somewhere ?
